version: "3.3"

services:
  mysqldb:
    image: 'mysql'
    container_name: mysqldb
    environment:
      - MYSQL_USER=nhatminh3004
      - MYSQL_PASSWORD=mysql
      - MYSQL_DATABASE=docker_db
      - MYSQL_ROOT_PASSWORD=root
    ports:
      - "3307:3306"
  springboot:
    container_name: springboot
    image: 'docker-spring-boot-mysql'
    restart: always
    build: .
    ports:
      - "8081:8080"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysqldb:3306/docker_db
      - SPRING_DATASOURCE_USERNAME=nhatminh3004
      - SPRING_DATASOURCE_PASSWORD=mysql
      - SPRING_JPA_HIBERNATE_DDL_AUTO=create
    depends_on:
      - mysqldb
