name: Deploy

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [main]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: Deploy using ssh
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: 22
          script: |
            cd /home/nhatminh3004/github_action_docker_spring_mysql/
            git pull origin main
            sudo docker-compose down
            sudo docker-compose up --build
            echo Build success
            
            # Wait for the application to start (you can adjust the waiting time as needed)
            sleep 30
            
            # Check if the application is accessible on port 8080
            response=$(curl -s -o /dev/null -w "%{http_code}" http://http://20.163.217.108/test)
            
            # Check if the response code is 200 (OK)
            if [ $response -eq 200 ]; then
              echo "Spring Boot application is running successfully."
              exit 0  # Success
            else
              echo "Spring Boot application failed to start or is not accessible on port 8080."
              exit 1  # Failure
            fi
